import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import '@marifa/ui/globals.css'
import { Providers } from '@/components/providers'
import { Toaster } from '@marifa/ui/components/sonner'
import { AnimatedThemeToggler } from '@marifa/ui/components/animated-theme-toggler'

const fontSans = Geist({
  subsets: ['latin'],
  variable: '--font-sans'
})

const fontMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-mono'
})

export const metadata: Metadata = {
  title: 'Better Nest Kit',
  description: 'Generated by create betternest-kit'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${fontMono.variable} font-sans antialiased`}
      >
        <Providers>
          <div className="absolute top-4 right-4 z-50">
            <AnimatedThemeToggler />
          </div>
          {children}
          <Toaster position="top-center" richColors />
        </Providers>
      </body>
    </html>
  )
}
