import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['cjs'],
  dts: true,
  clean: true,
  sourcemap: true,
  minify: true,
  shims: true,
  noExternal: [/(.*)/],
  external: [
    'events',
    'fs',
    'fs/promises',
    'path',
    'child_process',
    'util',
    'http',
    'https',
    'url',
    'stream',
    'zlib',
    'crypto',
    'os',
    'tty',
    'readline',
    'constants',
    'module',
    'assert',
    'buffer',
    'console',
    'process',
    'v8',
    'vm',
  ],
});
